name: Deploy Infrastructure

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # Build TypeScript extractor
      - name: Install dependencies and build extractor
        run: |
          cd serverless/extractor
          npm install
          npm run build

      # Build TypeScript status-getter  
      - name: Install dependencies and build status-getter
        run: |
          cd serverless/status-getter
          npm install
          npm run build

      - name: Install CDK and deps
        run: |
          python -m pip install --upgrade pip
          pip install -r infra/requirements.txt
          npm install -g aws-cdk

      - name: Deploy CDK Stacks
        env:
          AWS_ACCESS_KEY_ID:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION:    us-east-1
        run: |
          cd infra
          cdk deploy --all --require-approval never